### ISSUE TITLE
New release 1.0.5

### ISSUE THREAD

**Issue by jahaniam** [ros/rosbag_snapshot#32] opened 2023-09-08 17:26 UTC
Can we release a new version with the recent changes, please?

**Comment by DLu** [comment] 2023-09-08 19:16
Duplicate of #31 , but closes with https://github.com/ros/rosdistro/pull/38483

**Closed by DLu** 2023-09-08 19:16 UTC

**Comment by jahaniam** [comment] 2023-09-08 19:47
Thank you for your quick response!
